apiVersion: v1
kind: Pod
metadata:
  name: db-client
  labels:
    app: db-client
spec:
  containers:
    - name: db-client
      image: db-projeto:1
      ports:
        - containerPort: 5858
      envFrom:
        - configMapRef:
            name: db-configmap