apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: iamfukuma/nginx-projeto-dev:1
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod