name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        with:
          context: Projeto_dev/
          file: docker-compose.yml
          run: docker-compose --version -f docker-compose.yml up -d --build
        
