name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: debian:lasted
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Build the Docker image
        run: docker-compose --version -f docker-compose.yml up -d --build
